
name: Lint code

on: [pull_request, push]

jobs:
  lint-code:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
      # allow to error for now
      continue-on-error: true
